[[main]]
none = "none"

[[main]]
name = "Portfolio"
pageRef = "portfolio"
identifier = "portfolio"
weight = 9999

[[main]]
name = "Resume"
pageRef = "resume"
identifier = "resume"
weight = 8000

[[main]]
name = "About"
pageRef = "about"
identifier = "about"
weight = 1000

[[footer]]
none = "none"
