colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = false
enableCodeCopy = true
disableImageOptimization = false
disableImageZoom = true
disableTextInHeader = false
defaultBackgroundImage = "/img/diagonal.svg" # Default background image for both background homepage layout and background hero style
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true
defaultFeaturedImage = "/img/background.jpg" # Default background image for all featured images across articles, will be overridden by a local featured image.
logo = "/img/logo.png" # Logo in header
description = "Alejo Ramirez Gismondi personal website and portfolio. Experienced Software Engineer. Currently looking for work in Europe, especially roles related to Game Design and Game Development, Web3, Crypto or I+D+i." # For site metadata

[header]
layout = "fixed-fill-blur"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background" # page, profile, hero, card, background
showRecent = true
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/portfolio"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = "/img/diagonal.svg" # Image to be used in hero and card layouts

[article]
heroStyle = "background"
showDate = false
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = false
showPagination = false
invertPagination = false
showReadingTime = false
showTableOfContents = false
showTaxonomies = false
showAuthorsBadges = false
showWordCount = false
showZenMode = true
sharingLinks = [ "linkedin", "twitter", "whatsapp", "reddit", "email"]

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
